spring:
    datasource:
        password: Passw0rd
        url: jdbc:postgresql://localhost:5432/chess_db
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: false
rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem