package testUtil;

public enum TypeOfMoveEnum {
    BASIC_PAWN_MOVE,
    BASIC_WITH_PIECE_NAME,
    CASTLING,
    PAWN_PROMOTION,
    PAWN_PROMOTION_WITH_COLUMN,
    PIECE_TO_MOVE_WITH_ROW,
    PIECE_TO_MOVE_WITH_COLUMN
}
